### ISSUE TITLE
Add random restarts

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#10]
# DoD

- [ ] Have random restarts functionality, if necessary

# Tasks

- [ ] Implement functionality
  - [ ] Select n models at random to have them restart
    - [ ] initialise model with random standard deviation, likelihood
- [ ] Write tests
- [ ] Look further into:
```
def add_random_restarts(models, n_rand=1, sd=4, data_shape=None):
    new_models = []
    for a_model in models:
        for (kernel, likelihood, mean) in zip(add_random_restarts_single_k(a_model.kernel, n_rand=n_rand, sd=sd, data_shape=data_shape), \
                                              add_random_restarts_single_l(a_model.likelihood, n_rand=n_rand, sd=sd, data_shape=data_shape), \
                                              add_random_restarts_single_m(a_model.mean, n_rand=n_rand, sd=sd, data_shape=data_shape)):
            new_model = a_model.copy()
            new_model.kernel = kernel
            new_model.likelihood = likelihood
            new_model.mean = mean
            new_models.append(new_model)
return new_models 
```
