### ISSUE TITLE
Simplify Kernels and Remove redundancy

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#11]
This also enables us to do textual description.

# DoD

- [x] Assure that kerndisc never retries unnecessary models

# Tasks

- [x] Create criterions on when a model can be evaluated:
```
        current_models = [model.simplified() for model in current_models]
        current_models = ff.remove_duplicates(current_models)
```
with simplified being defined as:
```
    def simplified(self):
        k = self.copy()
        k_prev = None
        while not k_prev == k:
            k_prev = k.copy()
            k = k.collapse_additive_idempotency()
            k = k.collapse_multiplicative_idempotency()
            k = k.collapse_multiplicative_identity()
            k = k.collapse_multiplicative_zero()
            k = k.canonical()
return k
```
- [x] Remove duplicates after simplification
- [x] remove duplicates that were already scored (#22)
- [x] Testing
