### ISSUE TITLE
Remove duplicates

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#12]
# DoD

- [ ] Automatically remove duplicates from search space

# Tasks

- [ ] Look into difference between redundancies, duplicated in AS
  - [ ] Add more tasks here if there is a difference
