### ISSUE TITLE
Out Of Bound optimising functionality

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#14]
# DoD

- [ ] Apply `0 1` like prior to oob optimization
- [ ] Have documented somewhere what this means

# Tasks

- [X] Look what AS does here
- [X] Write down their procedure
- [ ] Implement
  - [ ] Test
