### ISSUE TITLE
Remove nan scored

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#15]
# DoD

- [x] Go trough models scores after training and remove nan scores

# Tasks

- [x] Implement this functionality
 - [x] Test
- [X]  Check whether AS does anything more than this -> it does not
