### ISSUE TITLE
Add stopping criterions

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#16]
# DoD

- [ ] Have selectable stopping criterions for search

# Tasks

- [ ] Implement stopping criterions
  - [ ] `max_depth`
  - [ ] didn't improve by more than ... percent (`no_improvment`)
  - [ ] ...
- [ ] Test
