### ISSUE TITLE
Re-add best model(s) to search space

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#18]
# DoD

- [ ] Have readd functionality
- [ ] Observe its performance compared to usual performance

# Tasks

It seems like AS never really used this functionality, as `best_models` is never set to anything else than `None`.

- [ ] Implement this
- [ ] Write tests
- [ ] Evaluate its performance gain vs search time

```
        if not best_models is None:
            for a_model in best_models:
                current_models = current_models + [a_model.copy()] + ff.add_jitter_to_models([a_model.copy() for dummy in range(exp.n_rand)], exp.jitter_sd)
```
