### ISSUE TITLE
Write Model selection and expansion loop

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#19]
# DoD

- [ ] Have List of models to be trained and evaluated in each loop 

# Tasks (#22)

- [x] (1) Expand current model (#21)
~- [ ] (2) Add random restarts (#10)~
- [x] (3) Add jitter (#13)
- [x] (4) Re-add best models (#18)
- [x] (5) shuffle for comp. distribution
