### ISSUE TITLE
Wrapup of scoring and training functionality

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#20]
# DoD

- [x] After cleaning results (removing nan etc), select winner(s)
- [x] Update search space with these

# Tasks

- [x] Implement the greedy search
- [x] Expand winners of search
