### ISSUE TITLE
Add CP and CW kernels

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#23]
# DoD

- [ ] Have working CP Kernel
- [ ] Have working CW Kernel

# Tasks (#25)

- [ ] Research how [gpflow issue](https://github.com/GPflow/GPflow/issues/453) does it
- [ ] Research how [as copies it from gpml](https://github.com/jamesrobertlloyd/gpss-research/blob/master/source/flexible_function.py)
- [ ] Create new kernel package
  - [ ] Implement CW kernel
  - [ ] Implement CP kernel
