### ISSUE TITLE
Add automatic textual description

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#26]
AS implements the ABCD framework for textual description/explanation of kernels generated by it. We also need this for simplified kernel expressions.

Relies on #11

# DoD

- [x] Have ability to describe a simplified kernel expression

# Tasks

- [x] Add `explanation` package to explain and describe kernels
- [x] Have explanation syntax and texts as described by Duvenaud et al.
