### ISSUE TITLE
Implement own version of Duvenauds Grammar

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#36]
There are some things that occurred during development and evaluation that might be improvements on the grammar of Duvenaud et al.
These improvements also don't seem to be covered in Lloyd et al.

It might be good to implement those in a `modified` version of duvenauds grammar, some small changes were already made that move away from Duvenauds design, these must then also be moved.

### Tasks

- [ ] Create new `_grammar_duvenaud_modified.py` grammar
- [ ] Implement/Move over base kernel exclusion
   (rationale: Stops GPs from just taking `constant` or `white` as the "best" result)
- [ ] Maybe make initial full expansion part of this grammar? Current implementation as part of `discover` might be unreasonable

TODO: Add more improvements noticed during development here.
