### ISSUE TITLE
Keep Kernels alive during the whole procedure?

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#38]
Research issue to check whether this might actually be a good idea

### Tasks

- [x] Check whether this is feasible
- [x] Implement if feasible
- [x] Jot down results here
