### ISSUE TITLE
Add time series scaling to preprocessing

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#41]
It seems to have an impact on a time series if it is very sparse and also stretches over a large time interval. Some of these examples include `39` data points over a duration of about 45k minutes (~75h).

This leads to:
* `kerndisc` tending to find `constant` and `white` kernels (as an end result) to deal with this,
* bad interpolations (function returns to some constant value in between pre conditioned points)

To tackle this behavior `kerndisc` should be able to rescale `X` to some interval during preprocessing.

This interval should still keep the same relative distance in between points.

### Tasks

- [x] Implement rescaling option for preprocessing
  - [x] Allow to rescale to some arbitrary, desired interval
  - [x] Allow automatic rescaling (e.g., `[0, ..., 49]` for `n=49` data points)
