### ISSUE TITLE
Implement`additive_form` AS

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#6]
# DoD

- [ ] Have method that simplifies kernels into additive form
- [ ] Method should return canonical representations

# Tasks

- [ ] Implement additive form method
  - [ ] Test
- [ ] Add option to enable this
- [ ] Reremove duplicates afterwords
