### ISSUE TITLE
Write scoring and training for `kerndisc`

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#7]
# DoD

- [x] Have working model evaluation
- [x] Have working training function

# Tasks

- [x] Find way to score models
  * Can be ML at first
- [x] Implement scoring
- [x] Implement training, invoke training as defined by `gpflow`
- [x] Determine parameter procedure
 * Think about converting to a truely bayesian env
