### ISSUE TITLE
Have functioning prototype of `kerndisc`

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#8]
# DoD

- [ ] Have functioning first version of `kernDisc`

# Tasks

- [ ] Finish all base tasks in this repo
- [ ] Have this run successfully on some time series
  - [ ] Make results of first run accessible
