### ISSUE TITLE
Create tasks necessary to be completed for `kernDisc`

### ISSUE THREAD

**Issue by BracketJohn** [BracketJohn/kernDisc#9]
# DoD

- [x] Have all new tasks in `kerndisc` repository

# Tasks 

- [x] Break down `kernDisc` construction into sub tasks
- [x] Create sub tasks
- [x] Specify dod, tasks in new sub tasks
- [x] Go trough current `automated-statistician`
  - [x] jot down it's abilities
  - [x] specify subset to realize in this new, smaller lib
